info:
  contact: {}
paths:
  /api/printers:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1,"data":[{"id":1,"status":"ok"}],"msg": "操作成功"}'
          schema:
            type: string
        "400":
          description: '{"code":1,"data":[],"msg": "操作失败"}'
          schema:
            type: string
      summary: 获取全部打印机
      tags:
      - 打印机
swagger: "2.0"
